[package]
name = "pdarena-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.3.2"
clap = { version = "3.2.17", features = ["derive"] }
tokio = { version = "1.20.1", features = ["full"] }
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
tokio-postgres = "0.7.6"
strum = { version = "0.24.1", features = ["derive"] }

auth-service-api = {version = "*", git = "https://github.com/innexgo/auth-service-api" }
reqwest = "0.11.11"
rand = "0.8.5"
base64 = "0.13.0"
tar = "0.4.38"
deadpool-postgres = "0.10.2"
futures-util = "0.3.23"
